name: Terraform Plan

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

concurrency:
  group: terraform-dev
  cancel-in-progress: false

env:
  TF_WORKING_DIR: environment/dev
  AWS_REGION: us-east-1
  ROLE_ARN: arn:aws:iam::646177707953:role/GithubTerrafrom

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest


    defaults:
      run:
        working-directory: ${{ env.TF_WORKING_DIR }}
    

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform FMT
        run: terraform fmt -check -recursive

      - name: Terraform Validate
        run: terraform validate

  plan:
    name: Plan
    needs: validate
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{ env.TF_WORKING_DIR }}

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform State List
        run: terraform state list || true

      - name: Create Plan 
        run: terraform plan -input=false -lock-timeout=30s -out=tfplan 

      - name: Generate Human Readable Plan 
        run: terraform show -no-color tfplan > tfplan.txt 
        
      - name: Upload Binary Plan 
        uses: actions/upload-artifact@v4 
        with: 
          name: terraform-plan 
          path: environment/dev/tfplan

      - name: Upload Plan Output 
        uses: actions/upload-artifact@v4 
        with: 
          name: terraform-plan-output 
          path: environment/dev/tfplan.txt

  apply:
    name: Apply
    needs: plan
    runs-on: ubuntu-latest
    environment:
      name: dev    

    defaults:
      run:
        working-directory: ${{ env.TF_WORKING_DIR }}

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Download Plan Artifact 
        uses: actions/download-artifact@v4 
        with: 
          name: terraform-plan 
          path: environment/dev 
      - name: Apply Approved Plan 
        run: terraform apply -auto-approve tfplan